version: '3'
services: 
    visualizer: 
        image: manomarks/visualizer
        ports:
            - 8000:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                    constraints: [node.role == manager] 
    portainer:
        image: portainer/portainer
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                    constraints: [node.role == manager]  

networks:
    gsite-app:
       external: true                    