version: '2'
services:
    gsite-app:
        image: gsite
        external_links:
            - gsite-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gsite
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gsite-mongodb:
        extends:
            file: mongodb.yml
            service: gsite-mongodb
