version: '2'
services:
    gsite-mongodb:
        container_name: gsite-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb gsite-mongodb-config
    gsite-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    gsite-mongodb-config:
        image: mongo:3.2.10
        container_name: gsite-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
