
spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    jackson:
        serialization.indent_output: true
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: gsite
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false


server:
    port: 8082

application:
    http:
        version: V_1_1
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: gsiteManager@localhost
        base-url: http://127.0.0.1:8082
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: gsiteManager
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            reportFrequency: 60
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false
