
spring:
    profiles:
        active: prod
        include: swagger
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            uri: mongodb://mongos:27017
            database: gsite
    thymeleaf:
        cache: true

server:
    port: 8082
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

application:
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 8a1d3b6fa9e302c0415b6d650e9911883f953fd3
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: giftsiteforyou@gmail.com
        base-url: http://gsite.cf
    ribbon:
            display-on-active-profiles: prod
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: gsite.cf
            port: 2003
            prefix: gsiteManager
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            reportFrequency: 60
    logging:
        logstash:
            enabled: false
            host: gsite.cf
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false
    cache:
        hazelcast:
            network:
                address: gsite-cache-member
