version: '3'
services:
# mongo config
    gsite-mongodb-config1:
        image: mongo:3.2.10
        command: mongod --configsvr --dbpath /data/db 
        networks: 
            gsite-db:
                aliases:
                    - mongoconfig1
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                    constraints: [node.role == manager]     
    gsite-mongodb-config2:
        image: mongo:3.2.10
        command: mongod --configsvr --dbpath /data/db
        networks: 
            gsite-db:
                aliases:
                    - mongoconfig2
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                    constraints: [node.role == worker]      
    gsite-mongodb-config3:
        image: mongo:3.2.10
        command: mongod --configsvr --dbpath /data/db 
        networks: 
            gsite-db:
                aliases:
                    - mongoconfig3
        deploy:
            restart_policy:
                condition: on-failure 
            placement:
                    constraints: [node.role == worker]        
# mongos                                                  
    gsite-mongodb-mongos:
        image: mongo:3.2.10
        ports:
            - 27017
        command: mongos --configdb mongoconfig1,mongoconfig2,mongoconfig3
        networks:
            gsite-app:
               aliases:
                    - mongos  
            gsite-db:
                aliases:
                    - mongos
        depends_on:
            - gsite-mongodb-config1
            - gsite-mongodb-config2
            - gsite-mongodb-config3
        deploy:
            replicas: 2
            update_config:
                parallelism: 1  
                delay: 10s
            restart_policy:
                condition: on-failure    
# shard 1                
    gsite-mongodb-shard1-rs1:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs1 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard1
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard1-rs2:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs1 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard1
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard1-rs3:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs1 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard1
        deploy:
            restart_policy:
                condition: on-failure
# shard 2                
    gsite-mongodb-shard2-rs1:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs2 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard2
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard2-rs2:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs2 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard2
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard2-rs3:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs2 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard2
        deploy:
            restart_policy:
                condition: on-failure
# shard 3                
    gsite-mongodb-shard3-rs1:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs3 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard3
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard3-rs2:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs3 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard3
        deploy:
            restart_policy:
                condition: on-failure
    gsite-mongodb-shard3-rs3:
        image: ainguyen/gsite-mongodb-shard
        command: mongod --replSet rs3 --smallfiles
        networks: 
            gsite-db:
                aliases:
                    - mongoshard3
        deploy:
            restart_policy:
                condition: on-failure    
# mongo express
    gsite-mongo-express:
        image: ainguyen/gsite-mongo-express
        ports:
            - 9001:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=gsite-mongodb-mongos
        depends_on:
            - gsite-mongodb-mongos
        networks: 
            - gsite-db
            - gsite-app
                 
networks:
    gsite-app:
       external: true
    gsite-db:
        driver: overlay