version: '2'

services:
  web:
    build: gsite-web
    image: gsite-web
    volumes: ["./gsite-web/static:/usr/share/nginx/html"]
    ports: ["80:80"]
    # environment:
    #   - "constraint:node==jcoucp0-ucpnode"

  api:
    build: gsite-dispatcher
    image: gsite-dispatcher

  api-java:
    build: gsite-java
    image: gsite-java
    external_links:
            - gsite-mongodb:mongodb
    environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gsite
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application

  gsite-mongodb:
        extends:
            file: mongodb.yml
            service: gsite-mongodb
