version: '2'
services:
    gsite-mongodb:
        container_name: gsite-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/gsite/mongodb/:/data/db/
